const productsData = [
  {
    id: 0,
    category: "rubik",
    name: "Mirror Cube",
    price: 250,
    image: "./img/rubik/mirror-cube.png",
  },
  {
    id: 1,
    category: "rubik",
    name: "3x3 Cube",
    price: 200,
    image: "./img/rubik/rubik.png",
  },
  {
    id: 2,
    category: "rubik",
    name: "Pyraminx",
    price: 300,
    image: "./img/rubik/pyraminx.png",
  },
  {
    id: 3,
    category: "rubik",
    name: "Megaminx",
    price: 400,
    image: "./img/rubik/megaminx.png",
  },
  {
    id: 4,
    category: "rubik",
    name: "Skewb",
    price: 150,
    image: "./img/rubik/skewb.png",
  },
  {
    id: 5,
    category: "ttrpg",
    name: "D&D Dungeon Master Guide",
    price: 60000,
    image: "./img/ttrpg/d&ddmg.png",
  },
  {
    id: 6,
    category: "ttrpg",
    name: "D&D Players Handbook",
    price: 60000,
    image: "./img/ttrpg/d&dphb.png",
  },
  {
    id: 7,
    category: "ttrpg",
    name: "D&D Monster Manual",
    price: 60000,
    image: "./img/ttrpg/d&dmm.png",
  },
  {
    id: 8,
    category: "ttrpg",
    name: "Call Of Cthulhu Investigators Handbook",
    price: 60000,
    image: "./img/ttrpg/cocih.png",
  },
  {
    id: 9,
    category: "ttrpg",
    name: "Call Of Cthulhu Keepers Rulebook",
    price: 60000,
    image: "./img/ttrpg/cockr.png",
  },
  {
    id: 10,
    category: "ttrpg",
    name: "Star Trek RPG Rulebook",
    price: 60000,
    image: "./img/ttrpg/star-trek-rpg.png",
  },
  {
    id: 11,
    category: "ttrpg",
    name: "7th Sea 2E Rulebook",
    price: 60000,
    image: "./img/ttrpg/7th-sea-rpg.png",
  },
  {
    id: 12,
    category: "ttrpg",
    name: "Avatar RPG Rulebook",
    price: 60000,
    image: "./img/ttrpg/avatar-rpg.png",
  },
  {
    id: 13,
    category: "ttrpg",
    name: "Blade Runner RPG Rulebook",
    price: 60000,
    image: "./img/ttrpg/blade-runner-rpg.png",
  },
  {
    id: 14,
    category: "ttrpg",
    name: "Doctor Who RPG Rulebook",
    price: 60000,
    image: "./img/ttrpg/doctor-who-rpg.png",
  },
  {
    id: 15,
    category: "ttrpg",
    name: "Dune RPG Rulebook",
    price: 60000,
    image: "./img/ttrpg/dune-rpg.png",
  },
  {
    id: 16,
    category: "ttrpg",
    name: "Lex Arcana RPG Rulebook",
    price: 60000,
    image: "./img/ttrpg/lex-arcana-rpg.png",
  },
  {
    id: 17,
    category: "ttrpg",
    name: "ShadowRun RPG Rulebook",
    price: 60000,
    image: "./img/ttrpg/shadowrun-rpg.png",
  },
  {
    id: 18,
    category: "ttrpg",
    name: "The One Ring Rulebook",
    price: 60000,
    image: "./img/ttrpg/the-one-ring.png",
  },
  {
    id: 19,
    category: "dice",
    name: "Negro Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-black-7-set.png",
  },
  {
    id: 20,
    category: "dice",
    name: "Rosa Claro 7 Dados",
    price: 150,
    image: "./img/dice/opaque-baby-pink-7-set.png",
  },
  {
    id: 21,
    category: "dice",
    name: "Azul Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-blue-7-set.png",
  },
  {
    id: 22,
    category: "dice",
    name: "Marron Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-brown-7-set.png",
  },
  {
    id: 23,
    category: "dice",
    name: "Verde Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-green-7-set.png",
  },
  {
    id: 24,
    category: "dice",
    name: "Marfil Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-ivory-7-set.png",
  },
  {
    id: 25,
    category: "dice",
    name: "Naranja Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-orange-7-set.png",
  },
  {
    id: 26,
    category: "dice",
    name: "Rosa Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-pink-7-set.png",
  },
  {
    id: 27,
    category: "dice",
    name: "Purpura Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-purple-7-set.png",
  },
  {
    id: 28,
    category: "dice",
    name: "Rojo Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-red-7-set.png",
  },
  {
    id: 29,
    category: "dice",
    name: "Blanco Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-white-7-set.png",
  },
  {
    id: 30,
    category: "dice",
    name: "Amarillo Opaco 7 Dados",
    price: 150,
    image: "./img/dice/opaque-yellow-7-set.png",
  },
  {
    id: 31,
    category: "rubik",
    name: "2x2 Cube",
    price: 200,
    image: "./img/rubik/2x2.png",
  },
  {
    id: 32,
    category: "rubik",
    name: "4x4 Cube",
    price: 300,
    image: "./img/rubik/4x4.png",
  },
  {
    id: 33,
    category: "rubik",
    name: "5x5 Cube",
    price: 300,
    image: "./img/rubik/5x5.png",
  },
  {
    id: 34,
    category: "rubik",
    name: "6x6 Cube",
    price: 300,
    image: "./img/rubik/6x6.png",
  },
  {
    id: 35,
    category: "rubik",
    name: "7x7 Cube",
    price: 300,
    image: "./img/rubik/7x7.png",
  },
  {
    id: 36,
    category: "manga",
    name: "Chainsaw Man 01",
    price: 300,
    image: "./img/manga/chainsawman01.png",
  },
  {
    id: 37,
    category: "manga",
    name: "Chainsaw Man 02",
    price: 300,
    image: "./img/manga/chainsawman02.png",
  },
  {
    id: 38,
    category: "manga",
    name: "Spy x Family 01",
    price: 300,
    image: "./img/manga/spyxfamily01.png",
  },
  {
    id: 39,
    category: "manga",
    name: "Spy x Family 02",
    price: 300,
    image: "./img/manga/spyxfamily02.png",
  },
  {
    id: 40,
    category: "manga",
    name: "Spy x Family 03",
    price: 300,
    image: "./img/manga/spyxfamily03.png",
  },
  {
    id: 41,
    category: "manga",
    name: "JoJo Phantom Blood 01",
    price: 300,
    image: "./img/manga/jojo1-phantomblood1.png",
  },
  {
    id: 42,
    category: "manga",
    name: "JoJo Battle Tendency 01",
    price: 300,
    image: "./img/manga/jojo2-battletendency1.png",
  },
  {
    id: 43,
    category: "manga",
    name: "JoJo Stardust Crusaders 01",
    price: 300,
    image: "./img/manga/jojo3-stardustcrusaders01.png",
  },
  {
    id: 44,
    category: "manga",
    name: "JoJo Diamond is Unbreakable 01",
    price: 300,
    image: "./img/manga/jojo4-diamondisunbreakable01.png",
  },
  {
    id: 45,
    category: "manga",
    name: "JoJo Vento Aureo 01",
    price: 300,
    image: "./img/manga/jojo5-ventoaureo01.png",
  },
  {
    id: 46,
    category: "manga",
    name: "JoJo Stone Ocean 01",
    price: 300,
    image: "./img/manga/jojo6-stoneocean01.png",
  },
];

const appState = {
  currentProductsIndex: 0,
  activeCategory: "rubik",
};
